apiVersion: apps/v1

kind: Deployment

metadata:
  name: log-output
  namespace: exercises

spec:
  replicas: 1

  selector:
    matchLabels:
      app: log-output

  template:
    metadata:
      labels: 
        app: log-output

    spec:
      volumes:
        - name: shared-status
          emptyDir: {}

        - name: config
          configMap:
            name: log-output-config

      containers:
        - name: writer
          image: andres09otero/log-output-writer:1.0.0
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/files

        - name: reader
          image: andres09otero/log-output-reader:1.2.0
          env:
            - name: PORT
              value: "3000"
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/files
            - name: config
              mountPath: /usr/src/app/config

