apiVersion: apps/v1

kind: Deployment

metadata:
  name: todo-app
  namespace: project

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-app-image-pvc

      containers:
        - name: todo-app
          image: andres09otero/todo-app:1.5.0
          env:
            - name: PORT
              value: "3000"
            - name: TODO_BACKEND_URL
              value: "http://todo-backend-svc:2345"
            - name: IMAGE_CACHE_DIR
              value: "/usr/src/app/image-cache"
            - name: PICSUM_URL
              value: "https://picsum.photos/1200"
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/image-cache
