apiVersion: apps/v1

kind: Deployment

metadata:
  name: todo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: todo-app

  template:
    metadata:
      labels:
        app: todo-app

    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todo-app-image-pvc

      containers:
        - name: todo-app
          image: andres09otero/todo-app:1.3.1
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: image-cache
              mountPath: /usr/src/app/image-cache
